/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function times2(input: Array<number>): Array<number>
export declare function walkWithCar(): Car
export declare class Car {
  name: string
  getName(): string
  setName(name: string): void
}
