/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function times2Num(num: number): number
export declare function fibb(pos: number): number
export declare function walkWithCar(): Car
export declare class Car {
  name: string
  getName(): string
  setName(name: string): void
}
